[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py310"
isort_known_first_party = ["sqllm"]

[[tool.pysen.lint.mypy_targets]]
  paths = ["sqllm/"]
